# Generated by Django 2.1.7 on 2019-02-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_estimatequestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstimateQuestion',
            new_name='Question',
        ),
    ]
